-- AlterTable
ALTER TABLE "Store" ADD COLUMN "labelMarginTopMm" DOUBLE PRECISION NOT NULL DEFAULT 3;
ALTER TABLE "Store" ADD COLUMN "labelMarginBottomMm" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Store" ADD COLUMN "labelMarginLeftMm" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Store" ADD COLUMN "labelMarginRightMm" DOUBLE PRECISION NOT NULL DEFAULT 1;
